<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Bookings Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1a1a1a; }
        .header { border-bottom: 3px solid #C9A84C; padding-bottom: 15px; margin-bottom: 20px; }
        .hotel-name { font-size: 22px; font-weight: bold; color: #C9A84C; }
        h2 { font-size: 16px; margin-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        thead th { background: #1a1a1a; color: #fff; padding: 8px 10px; font-size: 9px; text-transform: uppercase; letter-spacing: 1px; }
        tbody td { padding: 7px 10px; border-bottom: 1px solid #f0ede6; font-size: 10px; }
        tbody tr:nth-child(even) { background: #fafaf8; }
        .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #ddd; text-align: center; font-size: 10px; color: #888; }
        .summary { background: #f8f7f4; padding: 12px 15px; border-radius: 6px; margin-bottom: 20px; }
        .summary-grid { display: table; width: 100%; }
        .summary-item { display: table-cell; text-align: center; padding: 5px; }
        .summary-val { font-size: 18px; font-weight: bold; color: #C9A84C; }
        .summary-lbl { font-size: 9px; color: #888; text-transform: uppercase; letter-spacing: 1px; }
    </style>
</head>
<body>
    <div class="header">
        <div style="display:table;width:100%;">
            <div style="display:table-cell;">
                <div class="hotel-name">ROYAL CREST HOTEL</div>
                <div style="font-size:9px;color:#888;letter-spacing:2px;">ADMIN REPORT</div>
            </div>
            <div style="display:table-cell;text-align:right;vertical-align:middle;">
                <div style="font-size:13px;font-weight:bold;">Bookings Report</div>
                <div style="font-size:10px;color:#888;">{{ $dateFrom }} – {{ $dateTo }}</div>
                <div style="font-size:10px;color:#888;">Generated: {{ now()->format('M d, Y H:i') }}</div>
            </div>
        </div>
    </div>

    <div class="summary">
        <div class="summary-grid">
            <div class="summary-item"><div class="summary-val">{{ $bookings->count() }}</div><div class="summary-lbl">Total Bookings</div></div>
            <div class="summary-item"><div class="summary-val">{{ $bookings->where('status','confirmed')->count() }}</div><div class="summary-lbl">Confirmed</div></div>
            <div class="summary-item"><div class="summary-val">{{ $bookings->where('status','cancelled')->count() }}</div><div class="summary-lbl">Cancelled</div></div>
            <div class="summary-item"><div class="summary-val">₱{{ number_format($revenue,0) }}</div><div class="summary-lbl">Revenue</div></div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Booking #</th>
                <th>Guest</th>
                <th>Room</th>
                <th>Check-in</th>
                <th>Check-out</th>
                <th>Nights</th>
                <th>Amount</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($bookings as $b)
            <tr>
                <td>{{ $b->booking_number }}</td>
                <td>{{ $b->guest_name }}</td>
                <td>{{ $b->room->name ?? 'N/A' }}</td>
                <td>{{ $b->check_in->format('M d, Y') }}</td>
                <td>{{ $b->check_out->format('M d, Y') }}</td>
                <td style="text-align:center;">{{ $b->nights }}</td>
                <td style="text-align:right;">₱{{ number_format($b->total_amount,2) }}</td>
                <td>{{ ucfirst(str_replace('_',' ',$b->status)) }}</td>
            </tr>
            @empty
            <tr><td colspan="8" style="text-align:center;padding:20px;color:#888;">No bookings found in this period.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Royal Crest Hotel · Calasiao, Pangasinan · info@royalcresthotel.com · +63 75 123 4567</p>
        <p>This report was automatically generated by the Royal Crest Hotel Booking System</p>
    </div>
</body>
</html>
